export const allowedEmailLabels = [
  'Job Search/Applications',
  'Job Search/Assessments',
  'Job Search/Interview Requests',
  'Job Search/Job Alerts',
  'Job Search/Job Alerts/Software',
  'Job Search/Job Alerts/Backup Jobs',
  'Job Search/Job Boards',
  'Job Search/Networking',
  'Job Search/Recruiters',
  'Job Search/Rejections',
  'Work/Cornell',
  'Work/Jovanna - Spectrum / CMG / CRTMS',
  'Work/Meetings & Scheduling',
  'Work/Needs Responses',
  'Money & Admin/Credit & Accounts',
  'Money & Admin/Payments',
  'Money & Admin/Receipts',
  'Money & Admin/Taxes',
  'Learning & Tech/Courses',
  'Learning & Tech/Newsletters',
  'Learning & Tech/Tools',
] as const