export {
  GmailApiError,
  GmailClient,
  buildHeaderMap,
  createGmailClient,
  extractAttachments,
  extractMessageBody,
  getHeader,
  parseGmailMessage,
  parseGmailThread,
  queryGmailInbox,
} from "./gmail";

export type {
  GmailApiHeader,
  GmailApiLabel,
  GmailApiMessage,
  GmailApiMessagePart,
  GmailApiMessagePartBody,
  GmailApiThread,
  GmailAttachmentRef,
  GmailAuthOptions,
  GmailClientOptions,
  GmailGetMessageOptions,
  GmailHeaderMap,
  GmailInboxQueryResult,
  GmailLabelListResult,
  GmailListMessagesOptions,
  GmailMessageBody,
  GmailMessageFormat,
  GmailMessageListItem,
  GmailMessageListResult,
  GmailQueryInboxOptions,
  ParsedGmailMessage,
  ParsedGmailThread,
} from "./types";
